feat: show app name and icon of all patchable apps
ReVanced/revanced-manager pull request #1015
Opened 2023-07-12 08:23 UTC by TheAabedKhan

<img width="351" alt="image" src="https://github.com/revanced/revanced-manager/assets/39409020/fea066a8-059c-45b9-a805-3480bac9c724">

2023-07-12 09:51 UTC, PalmDevs submitted a review, later dismissed
Need some string changes as well as some backend changes.

2023-07-12 10:01 UTC, Ushie commented on assets/i18n/en_US.json
> +        "fetchAppInfoDialogText": "Note: Your IP address will be sent to the selected source to fetch the app icon and name.",
What about "exposed" instead of "sent"

2023-07-12 10:03 UTC, oSumAtrIX commented on lib/services/app_info_api.dart
> +          'Basic YXBpLXRvb2xib3gtZm9yLWdvb2dsZS1wbGF5OkNiVVcgQVVMZyBNRVJXIHU4M3IgS0s0SCBEbmJL'
Does this PR complement #508 in any way? The token should 100% be removed from version control. You don't commit tokens. At maximum the build system injects it from an environment variable. For ReVanced Manager though, even this shouldn't be done. Such code should be decoupled from ReVanced Manager.

2023-07-12 10:05 UTC, TheAabedKhan commented on lib/services/app_info_api.dart
> +          'Basic YXBpLXRvb2xib3gtZm9yLWdvb2dsZS1wbGF5OkNiVVcgQVVMZyBNRVJXIHU4M3IgS0s0SCBEbmJL'
It's the token of their official Google Chrome Extension. They won't remove it for sure.

2023-07-12 10:09 UTC, TheAabedKhan commented on lib/services/app_info_api.dart
> +          'Basic YXBpLXRvb2xib3gtZm9yLWdvb2dsZS1wbGF5OkNiVVcgQVVMZyBNRVJXIHU4M3IgS0s0SCBEbmJL'
It's the only way. I also thought the same that's why I asked on Discord if I could replace APKMirror with APKPure.

2023-07-12 10:10 UTC, TheAabedKhan commented on assets/i18n/en_US.json
> +        "fetchAppInfoDialogText": "Note: Your IP address will be sent to the selected source to fetch the app icon and name.",
>What about "exposed" instead of "sent"

Sounds good.

2023-07-12 10:17 UTC, TheAabedKhan commented on lib/services/app_info_api.dart
> +          'Basic YXBpLXRvb2xib3gtZm9yLWdvb2dsZS1wbGF5OkNiVVcgQVVMZyBNRVJXIHU4M3IgS0s0SCBEbmJL'
> Does this PR complement #508 in any way?
We can enable APK download support for the suggested versions as well

2023-07-12 13:10 UTC, oSumAtrIX commented on assets/i18n/en_US.json
> +        "fetchAppInfoDialogText": "Note: Your IP address may be exposed to the selected sources to fetch the app icon and name.",
```suggestion
        "fetchAppInfoDialogText": "External services will be used to fetch app metadata. Your IP address will be exposed to these services.",
```

2023-07-12 13:11 UTC, oSumAtrIX commented on lib/services/app_info_api.dart
> +Future<Map<String, dynamic>> getAppInfo(
This should be solved via abstraction.

2023-07-12 13:12 UTC, oSumAtrIX requested changes
Instead of saying "sources", say "services".

2023-07-28 15:25 UTC, Ushie commented
Is this considered ready to ship?

2023-08-10 09:14 UTC, RexSonic commented
You could ask https://twitter.com/ArtemR if they're okay with you using their token

2023-11-19 21:21 UTC, closed without merging