feat: improve clarity of the warning dialogs
ReVanced/revanced-manager pull request #1058
Opened 2023-07-27 13:30 UTC by validcube

### ✨ improve clarity of the warning dialogs

Replace the generic "Are you sure you want to ..." with unique one that explains what it does!!!!!

2023-07-30 04:53 UTC, Ushie commented
I don't approve of the new strings, I feel like it's violating some sort of semantic here

@PalmDevs could you take a look? it seems to focus more on the side effects of your action than the action itself

2023-07-30 05:36 UTC, PalmDevs requested changes
Needs some changes.

2023-07-30 05:36 UTC, PalmDevs commented on assets/i18n/en_US.json
> +        "deleteKeystoreDialogTitle": "Delete keystore?",
Does deleting this keystore cause the Manager to generate a new one? If so, do `Regenerate keystore?` instead or something in similar terms.

2023-07-30 05:36 UTC, PalmDevs commented on assets/i18n/en_US.json
> +        "resetStoredPatchesDialogText": "Restoring patches selection to default will cause all previously selected patches to be reset.",
This can simply be `Resetting patches selection will remove all selected patches.`

2023-07-30 05:36 UTC, PalmDevs commented on assets/i18n/en_US.json
> +        "deleteKeystoreDialogText": "Using new keystore will make the manager unable to update patched application that have been signed using old keystore.",
This can be `Patched apps signed with the old keystore will no longer be able to update.`

2023-07-30 05:37 UTC, PalmDevs commented
> I don't approve of the new strings, I feel like it's violating some sort of semantic here
> 
> @PalmDevs could you take a look? it seems to focus more on the side effects of your action than the action itself

Not really, it just needs shortening and more clarification.

2023-07-31 07:07 UTC, PalmDevs approved these changes
English strings look good.

2023-07-31 14:53 UTC, merged