feat(installer): redesign misc. options
ReVanced/revanced-manager pull request #1062
Opened 2023-07-29 12:53 UTC by validcube

## ✨ Redesign misc. options

This replace the 3 dots menu with buttons, improve visibility

![image](https://github.com/ReVanced/revanced-manager/assets/93124920/5b590e28-b998-4d4c-88c8-75502d90f4eb)

2023-07-29 12:56 UTC, Ushie commented
What'd you do to share?

2023-07-29 14:38 UTC, validcube commented on lib/ui/views/installer/installer_viewmodel.dart
> -        shareLog();
bruh

2023-07-30 04:56 UTC, Ushie commented
Use contained tonal icon buttons https://m3.material.io/components/icon-buttons/overview

2023-07-30 04:56 UTC, Ushie commented
Also @PalmDevs could you take a look at this?

2023-07-30 05:41 UTC, PalmDevs commented
I'd personally suggest using the already-existing [Bottom App Bar](https://m3.material.io/components/bottom-app-bar/overview) component.

2023-07-30 11:45 UTC, Ushie commented
I'd completely forgotten about that, looks perfect

2023-08-02 20:19 UTC, ILoveOpenSourceApplications commented
#886 can be closed if this is implemented right?

2023-08-02 20:20 UTC, oSumAtrIX approved these changes

2023-08-02 20:20 UTC, Ushie commented
> #886 can be closed if this is implemented right?

Yes

2023-08-03 20:59 UTC, Ushie requested changes
Use [Bottom App Bar](https://m3.material.io/components/bottom-app-bar/overview) for the patch result options

2023-08-09 03:38 UTC, Ushie commented
@PalmDevs Need a bit of help, what should the copy logs button do?:
- Copy logs as text
- Copy file uri with the logs as the content
- Open share menu (current behavior)


![image](https://github.com/ReVanced/revanced-manager/assets/79272171/fcb9587e-e9b4-4511-9b58-f099b0dfaceb)

2023-08-09 03:38 UTC, Ushie commented
Also, should the Install FAB contain a label? or should it be Icon only

2023-08-09 04:09 UTC, PalmDevs commented
> @PalmDevs Need a bit of help, what should the copy logs button do?:
> - Copy logs as text
> - Copy file uri with the logs as the content
> - Open share menu (current behavior)
> 
> [Screenshot]

I think the best choice would be to open a file picker to let the user save the logs. The user (if they want to share) can access their file manager and share it from there.

2023-08-09 04:15 UTC, PalmDevs commented
The icons should also be changed. The icon for exporting the APK should be "Save" (floppy disk icon), and the icon for saving log should be "Post add" icon. References are found on Google's Icons website.

2023-08-09 13:46 UTC, Ushie commented
![image](https://github.com/ReVanced/revanced-manager/assets/79272171/6443fdfb-f242-489b-a67d-20c61aa2c05d)

2023-08-09 16:05 UTC, ILoveOpenSourceApplications commented
> ![image](https://user-images.githubusercontent.com/79272171/259429746-6443fdfb-f242-489b-a67d-20c61aa2c05d.png)

This looks good but it would look even better if the style is similar to that of how bottom app bar is in Gmail app. When scrolling down the container disappears and when scrolled up the container reappears. Also the installation button can be similar to the compose button in Gmail app. When still will show the icon and "Install" text next to it and scrolling down will shrink it to just the icon.

Demo:

https://github.com/ReVanced/revanced-manager/assets/117499019/402975df-154a-4066-81c6-6cd09f0d704f

2023-08-09 16:07 UTC, Ushie commented
The FAB in BottomAppBar can't be shown separetely, its part of the BottomAppBar, if the BottomAppBar gets hidden then the FAB does too

2023-08-09 16:22 UTC, ILoveOpenSourceApplications commented
Under scrolling in guidelines,  my opinion is represented and can be seen in action. Please have a look at it. This FAB implementation can also benefit throughout the UI. When clicking the "Storage" button, "Patch" button and now "Install" button.

2023-08-09 19:24 UTC, Ushie commented
I looked into hiding on scroll, and I think the implementation is rather annoying just for something I personally think has no use in this context

Maybe if @validcube wants to add hide on scroll, they can but I personally wont (I dont know flutter enough to do it in a way I think is good code)

As for using Tonal IconButtons, I tried both standard and tonal versions and I prefer tonal, I don't see specs that speak against using it

2023-08-10 12:02 UTC, merged