feat: abort patching process at any time
ReVanced/revanced-manager pull request #1072
Opened 2023-08-02 16:57 UTC by TheAabedKhan

This PR aims to allow users to abort the patching process whenever they want so that they can include/exclude patches or change the app without having to restart the manager.

2023-08-02 17:28 UTC, oSumAtrIX commented
Does this kill the patcher thread?

2023-08-03 08:15 UTC, TheAabedKhan commented
> Does this kill the patcher thread?

Yes. The user can only exit the page after the thread is stopped safely.

2023-08-03 20:55 UTC, Ushie commented on android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
> +                    // Signer("ReVanced", "s3cur3p@ssw0rd").signApk(patchedFile, outFile, keyStoreFile)
you could delete this comment

2023-08-03 20:57 UTC, Ushie requested changes

2023-08-03 20:57 UTC, Ushie commented on android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
>                  // Signer("ReVanced", "s3cur3p@ssw0rd").signApk(patchedFile, outFile, keyStoreFile)
You can delete this comment

2023-08-03 20:57 UTC, Ushie commented on android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
> +    private var run: Boolean = true
```suggestion
    private var cancel: Boolean = true
```

Maybe rename this to cancel so the if statements are more straightforward with their purpose?

2023-08-03 21:40 UTC, merged

2023-08-28 07:39 UTC, ILoveOpenSourceApplications commented
Has this been reverted or something as I cannot see the option to abort/cancel after clicking the patch button.

2023-08-28 12:07 UTC, oSumAtrIX commented
You can cancel by pressing back.