chore: merge `dev` to `main`
ReVanced/revanced-manager pull request #1077
Opened 2023-08-03 02:24 UTC by Ushie

2023-08-03 02:24 UTC, merged

2023-08-03 03:50 UTC, ILoveOpenSourceApplications commented on pubspec.yaml
Shouldn't it be 
```java
version: 1.5.1+100500001
```  
?

2023-08-03 03:52 UTC, ILoveOpenSourceApplications commented
I didn't mean to be a reviewer, just a simple doubt considering the previous versions. Also after this commit was pushed, the previous release has also disappeared.

2023-08-03 04:45 UTC, validcube commented on pubspec.yaml
It should :skull:

2023-08-03 04:46 UTC, validcube commented on pubspec.yaml
> Shouldn't it be 
> ```java
> version: 1.5.1+100500001
> ```  
> ?

@Ushie

2023-08-03 04:47 UTC, validcube requested changes
See comment

2023-08-03 15:01 UTC, Ushie commented on pubspec.yaml
The versioncode doesn't matter, it was the way it was for the Semantic Releases CI, which we no longer use, and as it doesn't matter there's no need to put more effort than just bumping it by 1

2023-08-03 15:02 UTC, Ushie commented
> I didn't mean to be a reviewer, just a simple doubt considering the previous versions. Also after this commit was pushed, the previous release has also disappeared.

Both releases contained upstream bugs, the correct way would've been to downgrade ReVanced Patcher to 11.0.4 and make a new release though, but it's fine

2023-08-04 04:38 UTC, ILoveOpenSourceApplications commented
Why downgrade the ReVanced Patcher version though?

2023-08-04 11:03 UTC, Ushie commented
The ReVanced Patcher is where the issues where introduced in