add docs to readme and small fixes
ReVanced/revanced-manager pull request #1264
Opened 2023-09-13 01:17 UTC by KobeW50

closes https://github.com/ReVanced/revanced-manager/issues/962

2023-09-13 01:18 UTC, Ushie commented
Please rebase your PR ontop of the latest dev commit

2023-09-13 01:19 UTC, oSumAtrIX commented
Apparently is already.

2023-09-13 01:20 UTC, Ushie commented
It reverts changes of d1218616ec870edbaced6fd19dd6a2a779c73968

2023-09-13 01:21 UTC, oSumAtrIX requested changes

2023-09-13 01:21 UTC, oSumAtrIX commented on README.md
> +To download ReVanced Manager, go [here](https://github.com/revanced/revanced-manager/releases/latest) and install the provided APK file.
"Go here" is weird.

2023-09-13 01:21 UTC, oSumAtrIX commented on README.md
> +2. Does not work on some armv7 devices
```suggestion
2. Does not work on some ARMv7 devices
```

2023-09-13 01:21 UTC, oSumAtrIX commented on README.md
> +If you wish to discuss the Manager, a thread has been made under the [#development](https://discord.com/channels/952946952348270622/1002922226443632761) channel in the Discord server. Please note tha
This should be removed as staged in dev.

2023-09-13 01:21 UTC, oSumAtrIX commented on README.md
> +If you wish to translate ReVanced Manager, we're accepting translations on [Crowdin](https://translate.revanced.app)
It is unnecessary to question if you wish to translate.

```suggestion
We're accepting translations on [Crowdin](https://translate.revanced.app)
```

2023-09-13 01:22 UTC, oSumAtrIX commented
> It reverts changes of [d121861](https://github.com/ReVanced/revanced-manager/commit/d1218616ec870edbaced6fd19dd6a2a779c73968)

Well, thats what they PR'd. Not sure about their intention though.

2023-09-13 01:22 UTC, Ushie commented
Their changes are based on main, but target dev

2023-09-13 01:23 UTC, oSumAtrIX commented
The PR source branch is based on `dev` with a reverting commit on top.

2023-09-13 01:24 UTC, KobeW50 commented
Im a dumbass. I must've edited the main branch and then put it on the dev

2023-09-13 01:25 UTC, oSumAtrIX commented
Simply drop the last commit and commit a new one.

2023-09-13 05:34 UTC, KobeW50 commented
I dont use git so i couldn't figure how to drop a commit. But the current file changes should be good now

2023-09-15 15:10 UTC, validcube requested changes
Bloop

2023-09-15 15:10 UTC, validcube commented on README.md
> +3. Add your GitHub token in gradle. Properties like [this](/docs/4_building.md)
❗Should be called `gradle.properties`, not `gradle. Properties`

```suggestion
3. Add your GitHub token in gradle.properties like [this](/docs/4_building.md)
```

2023-09-16 08:47 UTC, validcube approved these changes
🥞 Changes to the readme file been approved.

Thank you for your contribution!

2023-09-16 10:38 UTC, merged

2023-09-18 00:24 UTC, KobeW50 commented
Thank you @validcube ❤️