feat: follow the system theme
ReVanced/revanced-manager pull request #1279
Opened 2023-09-20 17:19 UTC by BenjaminHalko

fixes: #1260

2023-09-20 17:21 UTC, BenjaminHalko commented
https://github.com/ReVanced/revanced-manager/assets/73490201/b81bb9aa-ebb4-46bd-81b1-7e84275f7a1f

2023-09-20 17:22 UTC, oSumAtrIX commented
Wondering if this is following correct M3 specs.

PS: Banger wallpaper

2023-09-20 17:28 UTC, Ushie commented
Instead of a DropDown button, you can use a FilledTonalButton and a popup, it looks much better

2023-09-20 17:37 UTC, BenjaminHalko commented
@Ushie I am assuming a popup of radio buttons?

2023-09-20 17:37 UTC, Ushie commented
yep!

2023-09-20 18:20 UTC, BenjaminHalko commented
@Ushie Something like this:
![Screenshot_20230920-111849_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/7af1984a-85a8-45df-afbc-495a872b55a4)

2023-09-20 18:22 UTC, Ushie commented
It needs to have an apply and cancel button, and you could add an icon to the popup title maybe

This is how the old revanced manager codebase had it 
![SmartSelect_20230920_212207_Hyperion](https://github.com/ReVanced/revanced-manager/assets/79272171/c6f4c1cf-36e1-4290-aa26-98225bca1e5c)

2023-09-20 18:32 UTC, BenjaminHalko commented
@Ushie Does it really need a cancel button though? Who is going to want to cancel their theme change...

2023-09-20 18:35 UTC, Ushie commented
I believe according to m3 guidelines the only time you provide the user with a single action is when it's an acknowledgement popup, not an action

2023-09-20 18:37 UTC, Ushie commented
It's a material design icon, I believe that specific one is Icon.palette, you can use it like other icons are used across the app

2023-09-20 18:38 UTC, PalmDevs commented
Yep, exactly as what Ushie said. Make sure the buttons are all text buttons though. No need for a filled button.

2023-09-20 18:38 UTC, Ushie commented
@PalmDevs Should this dialog include a title icon? no other dialog in the app does, it may be better to not include one just for the sake of consistency at the moment

2023-09-20 18:39 UTC, PalmDevs commented
> @PalmDevs Should this dialog include a title icon? no other dialog in the app does, it may be better to not include one just for the sake of consistency at the moment 

Technically, all dialogs should have an icon; but if no dialogs have it, don't include it for this one specific dialog.

2023-09-20 18:39 UTC, Ushie commented
Generally the current popups in the app aren't consistent in any way so we could have one PR refactoring all the popups, I could also probably pair that with a settings refactor because settings are currently in a horrible state

2023-09-20 18:41 UTC, PalmDevs commented on assets/i18n/en_US.json
All dialogs in M3 use `Sentence case`, so change this to `App theme`.

2023-09-20 18:42 UTC, PalmDevs commented on assets/i18n/en_US.json
> +        "themeModeHint": "Select the theme to use",
This is not required. Don't include any supporting text at all.

2023-09-20 18:42 UTC, PalmDevs commented on assets/i18n/en_US.json
> +        "themeModeLabel": "App Theme",
All dialog headlines in M3 use `Sentence case`, so change this to `App theme`.

2023-09-20 18:43 UTC, PalmDevs requested changes
The design should ideally look exactly like what Ushie's sent in the screenshot. Except only use text buttons, filled button isn't necessary. Also needs a few string changes.

2023-09-20 18:44 UTC, BenjaminHalko commented
Why not filled buttons, the other dialogs have them.

2023-09-20 18:46 UTC, PalmDevs commented
> Why not filled buttons, the other dialogs have them.

We don't need to point the user to click on one specific option as clicking on both does no harm.

2023-09-20 18:49 UTC, BenjaminHalko commented
how's this:
![Screenshot_20230920-114831_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/6c9dca67-81d3-4e88-b2ef-8139dcbb1cf7)

2023-09-20 18:50 UTC, BenjaminHalko commented
also, pressing back on the navbar acts like the user has pressed ok, because chances are they would rather keep the changed theme than revert back.

2023-09-20 18:52 UTC, BenjaminHalko commented
Honestly I think that it should have a subtitle as everything else has one, or is it just me....

2023-09-20 18:53 UTC, BenjaminHalko commented
Also, I think the ok button should be filled for consistency but again, it might be just me...

2023-09-20 18:53 UTC, Ushie commented
> also, pressing back on the navbar acts like the user has pressed ok, because chances are they would rather keep the changed theme than revert back.

that's unexpected behavior, we shouldn't stray away from what's the norm

the only time changes are applied is with the confirm button, anything else is a dismissal

2023-09-20 18:56 UTC, BenjaminHalko commented
@Ushie fair, though I think when `DynamicTheme` is changed it is saved automatically. (separate from the individual material you and light/dark setting) so I will have to find out how to stop it from auto saving...

2023-09-20 18:58 UTC, Ushie commented
I don't think I understand

2023-09-20 19:02 UTC, BenjaminHalko commented
I disabled the line that saves the theme:
```
Future<void> setThemeMode(BuildContext context, int value) async {
    //await _managerAPI.setThemeMode(value);
    final bool isDynamicTheme = DynamicTheme.of(context)!.themeId.isEven;
    await DynamicTheme.of(context)!.setTheme(value * 2 + (isDynamicTheme ? 0 : 1));
    final bool isLight = value != 2 && (value == 1 || DynamicTheme.of(context)!.theme.brightness == Brightness.light);
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        systemNavigationBarIconBrightness:
        isLight ? Brightness.dark : Brightness.light,
      ),
    );
    notifyListeners();
  }
  ```
  And you can see that the button displaying the current theme doesn't change from System, yet it still remembers the theme.
https://github.com/ReVanced/revanced-manager/assets/73490201/1dab0d6a-bdf0-42a6-b3e6-701b123b99af

2023-09-20 19:35 UTC, BenjaminHalko commented
@Ushie If I tell it to revert the theme on back button press, will it still matter that technically if you exit out of the app in the theme dialog it will retain your new theme despite not saving?

2023-09-20 19:36 UTC, Ushie commented
Are you doing that to be able to live-preview? you should make it so that it applies it on confirm, no need to apply it when a radio button is clicked

2023-09-20 20:09 UTC, BenjaminHalko commented
Ok then, sure thing!

2023-09-20 20:28 UTC, BenjaminHalko commented
@Ushie done.

I still think the OK button should be filled.

2023-09-20 20:32 UTC, Ushie commented
Sure, you can do that to make it consistent with other popups for the time being

2023-09-20 21:38 UTC, Ushie commented
Could you remove the weird padding around the radio button list? I hate how android does that, you can remove it the same way I removed it in the [installer type dialog](https://github.com/ReVanced/revanced-manager/pull/1062/files#diff-6ef035c5b3abb583a047adaa0263fce17ed343f3a871d60aab2beac59f076ef1R171)

2023-09-20 21:46 UTC, BenjaminHalko commented
@Ushie is this better?
![Screenshot_20230920-144510_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/3d902d9d-1050-442d-8867-cc45b7c68a6c)

2023-09-20 21:49 UTC, Ushie commented
Looks better to me, @PalmDevs what do you think?

2023-09-20 23:12 UTC, PalmDevs commented
> @Ushie is this better?
> ![Screenshot_20230920-144510_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/3d902d9d-1050-442d-8867-cc45b7c68a6c)
> 

Can you decrease the gap between the radio button and the text to be equal to the padding of the dialog?

2023-09-20 23:26 UTC, BenjaminHalko commented
@PalmDevs do you know how to decrease that padding?

2023-09-20 23:29 UTC, BenjaminHalko commented
I searched it up and apparently there is no way to decrease that padding....

2023-09-20 23:30 UTC, BenjaminHalko commented
We can add padding to the others so it balances out.....

2023-09-20 23:30 UTC, Ushie commented
I think it'll be fine like this, the install type dialog also looks like this

2023-09-20 23:31 UTC, BenjaminHalko commented
I do fine it odd that the space on the left of the radio button is slightly less that to the right between the text...

2023-09-20 23:33 UTC, BenjaminHalko commented
This looks better to me personally:
![Screenshot_20230920-163303_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/b3a82764-1513-453a-a78e-bc257a7dbf6a)

2023-09-20 23:36 UTC, Ushie commented
If you go with that instead, you should also update the padding on the installer one

2023-09-20 23:36 UTC, BenjaminHalko commented
I agree, if we do that should I open a new PR or just include it in this

2023-09-20 23:37 UTC, Ushie commented
Hm, I just remembered that installer dialog includes a title icon actually

2023-09-20 23:38 UTC, Ushie commented
Try removing the padding and adding the title icon we mentioned earlier in this thread, it might look better then

2023-09-20 23:41 UTC, BenjaminHalko commented
`Icons.palette` gives this icon which is different than the one shown in the picture you sent, but it still works.

![Screenshot_20230920-163946_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/e25b45ab-4c0b-4654-abff-725c0def940d)

2023-09-20 23:41 UTC, Ushie commented
Ah no, I meant remove the extra padding you added in your last preview

2023-09-20 23:48 UTC, BenjaminHalko commented
![Screenshot_20230920-164453_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/40097ccc-8a28-4876-921e-7601f5590872)

Though I personally like this one better as the padding between the edges and text are the same:
![Screenshot_20230920-164658_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/d318480b-8460-485e-9746-0e2efc97e73c)

2023-09-20 23:49 UTC, BenjaminHalko commented
There is also this problem we have to take into account:
![Screenshot_20230920-164846_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/d113eab1-a66a-4480-8339-9b5358a27117)

2023-09-20 23:49 UTC, Ushie commented
Alright, you can update the installer one aswell and push your changes

2023-09-20 23:50 UTC, BenjaminHalko commented
Sounds good

2023-09-20 23:50 UTC, Ushie commented
> There is also this problem we have to take into account: ![Screenshot_20230920-164846_ReVanced Manager Debug](https://user-images.githubusercontent.com/73490201/269444790-d113eab1-a66a-4480-8339-9b5358a27117.png)

Hm, I think radiolists in dialogs are meant to be scrollable, let me show you an example

I'm not sure how to do that in Flutter though

2023-09-20 23:51 UTC, BenjaminHalko commented
I think using `SingleChildScrollView`

2023-09-20 23:52 UTC, Ushie commented
<img width="578" alt="unnamed (4)" src="https://github.com/ReVanced/revanced-manager/assets/79272171/850304e2-24ce-44fb-bbd1-27e86d36dd7b">

2023-09-20 23:52 UTC, BenjaminHalko commented
fixed:
![Screenshot_20230920-165221_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/d36dca30-eaa5-473a-bbc5-fcebebb4882a)

2023-09-20 23:54 UTC, Ushie commented
Looks good to me, since that change should also be done in installer type's dialog you should push the changes relevant to theme picker only and a followup commit in the dev branch for installer type

2023-09-21 00:24 UTC, Ushie approved these changes

2023-09-21 00:25 UTC, merged