feat: root status in export patch log
ReVanced/revanced-manager pull request #1407
Opened 2023-10-18 09:42 UTC by validcube

## Root status in export patch log
This add root status to the log.

### 📱 Testing 
* (Recently out of or still) Draft stage, no testing is done. Only static analysis.

2023-10-18 09:45 UTC, validcube commented on lib/ui/views/installer/installer_viewmodel.dart
> +      'Roo: ${isRooted ? 'Yes' : 'No'}',
```suggestion
      Root permissions: ${isRooted ? 'Yes' : 'No'}',
```

2023-10-18 16:47 UTC, Ushie requested changes
Please make sure not to let your formatter remove the empty lines from the log, they're there for readability

2023-10-18 16:49 UTC, validcube commented
> Please make sure not to let your formatter remove the empty lines from the log, they're there for readability

Was going to do that once I'm available, thank for the heads up 👍

2023-10-20 08:10 UTC, validcube reviewed
Bleep

2023-10-20 08:10 UTC, validcube commented on lib/ui/views/installer/installer_viewmodel.dart
> +      Root permissions: ${isRooted ? 'Yes' : 'No'}',
```suggestion
      Root permissions: ${isRooted ? 'Yes' : 'No'}',
      
```

2023-10-20 08:12 UTC, validcube reviewed
Bloop

2023-10-20 08:12 UTC, validcube commented on lib/ui/views/installer/installer_viewmodel.dart
> +      Root permissions: ${isRooted ? 'Yes' : 'No'}',
```suggestion
      'Root permissions: ${isRooted ? 'Yes' : 'No'}',
```

2023-10-21 10:20 UTC, Ushie approved these changes

2023-10-21 10:46 UTC, merged