feat!: ReVanced Manager Compose
ReVanced/revanced-manager pull request #1409
Opened 2023-10-20 21:26 UTC by Axelen123

# TODO

- [ ] Update documentation and README
- [ ] Finish implementing and test app updates
- [ ] Update the `compose-dev` branch so it can be merged into `dev`

2023-10-21 05:15 UTC, PalmDevs commented
Thank you for your contribution but I do not agree with your decision to use Jetpack Compose. I am closing the PR. Please use React Native next time. Cheers! :trollface:

2023-10-23 17:54 UTC, kazimmt commented
`import app.revanced.manager.R`
in MainActivity.kt

2023-10-23 18:08 UTC, Ushie commented
Did you sync gradle?

2023-10-23 18:10 UTC, kazimmt commented
> Did you sync gradle?

YES
![](https://github.com/ReVanced/revanced-manager/assets/82371061/47a26541-fbb7-4f38-a7dd-258209a9a839)

2023-10-23 18:11 UTC, Ushie commented
What does it say when you hover over the R

2023-10-23 18:16 UTC, Ushie commented
Click the one at the top, import

2023-10-23 18:23 UTC, kazimmt commented
> Click the one at the top, import

Resolved.
Issue was from my side. Sorry

2025-07-23 08:25 UTC, brosssh commented
By the way, should this be `feat!:`?

2025-10-01 19:55 UTC, validcube requested changes
Hold, I think something is missing, give me two minutes.

cc: #2761

2025-10-02 15:14 UTC, merged

2025-10-02 15:14 UTC, validcube commented
:guh:

2025-10-02 15:17 UTC, Axelen123 commented
wdym guh???