feat: patch history
ReVanced/revanced-manager pull request #1414
Opened 2023-10-21 20:16 UTC by BenjaminHalko

closes: #643 

Adds patch history: It will keep the last 3 APKs of the patched packages. The user can then install or export it.

The UI could use a bit of work though. Right now if you click on the app in the history menu, it will let you install or export. If you open it in the installed app list you get the option to open / uninstall the app like before.

The reason for the 2 separate menus is for the case where someone patches the app, then closes manager without installing. It would be nice to be able to go back and install it. Thus it needs a separate entry from the version that is currently installed on the system.

The history is limited to the 3 most recent packages because it has to keep the patched apk for every entry which uses up space.

Example where Twitch was compiled but not installed, and where Repair Toolkit was compiled and installed:

https://github.com/ReVanced/revanced-manager/assets/73490201/ce041dac-41f7-41e0-a9f7-9b67d85216f0

2023-10-21 20:23 UTC, Ushie commented
You may be interested in adding chips to switch between those cards, look at older versions of revanced manager before the removal of the "update" WIP card

2023-10-21 20:26 UTC, validcube commented
Now we need "delete stored APK" in settings!!!!

2023-10-21 20:48 UTC, oSumAtrIX commented
This feature requires enhanced transparency. Users should be able to create a backup of the patched app once the patching process is complete. This could lead to significant storage consumption for each patched app by default. A checkbox labelled "Save a copy" should be included within the installation dialogue, accompanied by the subtitle: "A copy of the patched app will be saved, which can be installed or exported in the future. You can manage these copies in the 'Patched apps' section located in the main menu of ReVanced Manager." As suggested by @validcube, it is advisable to provide the option to delete saved APKs, preferably within the same interface where users can install, export, or manage the patched app. A submenu displaying the list of saved patched apps, their patching date, and metadata, including applied patches, should be available for that.

If the user checks the checkmark to save the patched app, but a saved patched app of the same version is already present, give the user the option to overwrite any existing saved app.

The installation button in the patched app view has to show the same popup as the one after patching, as you may want to mount the app.

2023-10-22 19:36 UTC, BenjaminHalko commented
> This could lead to significant storage consumption for each patched app by default
I propose we only save the last 3 packages, plus there could be an option when you click on an app in the history to delete it.

> A checkbox labelled "Save a copy" should be included within the installation dialogue, accompanied by the subtitle: "A copy of the patched app will be saved, which can be installed or exported in the future. You can manage these copies in the 'Patched apps' section located in the main menu of ReVanced Manager."
How about just a toggle in the settings menu. I feel like the patch history should be used for the event where a user forgets to either export or install an app. There have been a few times where I have forgot to export my apk and then needed to repatch it. But never an event where I wanted the app to save it for me. If I needed it saved, I just exported the apk. If I had to click a checkbox every time I wanted the app to save the apk, that would defeat the point of having the app save a backup.

> The installation button in the patched app view has to show the same popup as the one after patching, as you may want to mount the app.
Already should do that, though I don't have root so I can't test that out.

2023-10-23 19:40 UTC, oSumAtrIX commented
> I propose we only save the last 3 packages

How about using that as a maximum, but still inform the user about being able to overwrite the last saved patched app via a checkmark if a patched app is already saved? That way the user can replace their last saved patched app every time they successfully patch without having to manually clean up.

>  If I remembered to click a checkbox then I will have remembered to export the apk.

In this case, how about checking it by default. Having to visit the settings to toggle it, would be difficult right from the patch result screen.

2023-10-23 22:19 UTC, BenjaminHalko commented
The "3 packages" limit would be 3 different packages. If you patch youtube it would replace youtube in the history automatically. If the youtube package was not in the history it would bump the oldest package off the history.

Although, thinking about it now, since the patch history is for "if the user forgets to preform an action once finished patching" it might be simpler to save ONLY the last patched apk. There isn't really a need to save more than that.

2023-10-25 14:37 UTC, oSumAtrIX commented
> There isn't really a need to save more than that.

Yeah, 1 backup per app should be enough, saving the last patched app only (give the user the choice not to), should be good too.

2023-11-19 21:26 UTC, Ushie commented
I'm closing this PR, the use case is very niche and the development time would better be spent in the compose-dev branch, I think that's better than spending the development and review time for a feature that will be short-lived

Very sorry, I know you were specifically assigned this, but the issue you were assigned was misunderstood at the time you were assigned to this

2023-11-19 21:27 UTC, Ushie commented
This PR can be re-opened, if you choose to finish it

2023-11-20 16:49 UTC, oSumAtrIX commented
Reopening as this PR is nearly finished.

2023-11-21 03:04 UTC, BenjaminHalko commented
I'll try to finish it soon, just been busy with life lately. Sorry about that!

2023-11-25 19:10 UTC, BenjaminHalko commented
All done!

2023-11-25 19:36 UTC, BenjaminHalko commented
Now only 1 app is stored, you have the option to delete it by going into it's menu (same place where you would install/export, and you can now disable saving the app altogether in the settings.

2023-11-28 21:58 UTC, Ushie commented
Requesting the review of osumatrix who's worked more closely with this, I can't thoroughly review the backend

2023-11-30 14:59 UTC, oSumAtrIX requested changes
I suggest to consolidate the patched and installed apps sections to a "Patched apps" section. Installed patched apps list items can be distinct from not installed patched apps.

@PalmDevs Could you look into UI in this regard?

2023-12-14 15:02 UTC, PalmDevs commented
@BenjaminHalko Can you upload a recording of what the feature looks like now? Or is the video in the PR description already up-to-date?

2023-12-14 16:59 UTC, BenjaminHalko commented
Not shown in the video is the fact that only the last patched app gets saved. If there is already an app in the slot, it will get removed once a new app is done patching.

https://github.com/ReVanced/revanced-manager/assets/73490201/384eeec2-f954-40e3-a70f-237157e0ea1f

2024-01-14 02:38 UTC, oSumAtrIX commented on assets/i18n/en_US.json
> +        "patchHistoryHint": "Save the last patched app to install or export later",
```suggestion
        "patchHistoryHint": "Save the last patch to install or export later",
```

2024-01-14 02:38 UTC, oSumAtrIX commented on assets/i18n/en_US.json
> +        "patchHistorySubtitle": "Last patched app",
```suggestion
        "patchHistorySubtitle": "Last patch",
```

2024-01-14 02:42 UTC, oSumAtrIX reviewed
I am not sure about this suggestion, but currently, what "Last patched app" means can be confusing to the user. Is it the now-installed app? If you press delete, will it delete my currently installed patched app? Maybe add text to the app view that explains, that it is a backup of the last patched application

2024-03-05 16:45 UTC, BenjaminHalko commented
Added this description:
![Screenshot_20240305-084404_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/f5dd55de-e087-4913-87ef-462828cd7692)

2024-03-20 13:28 UTC, validcube commented
Is there anything that's holding up this PR?

2024-03-24 18:12 UTC, BenjaminHalko commented
I guess just approval.

2024-03-24 18:18 UTC, oSumAtrIX commented
https://github.com/ReVanced/revanced-manager/pull/1414#pullrequestreview-1820135060

Has this been resolved?

2024-06-26 03:17 UTC, ILoveOpenSourceApplications commented
> [#1414 (review)](https://github.com/ReVanced/revanced-manager/pull/1414#pullrequestreview-1820135060)
> 
> Has this been resolved?

@BenjaminHalko ?

2024-06-26 03:19 UTC, BenjaminHalko commented
@ILoveOpenSourceApplications I'll check tmr.

I think some text just needs to be changed.

2024-06-27 21:40 UTC, oSumAtrIX commented
Is it possible to display how much storage the last saved patched app takes?

2024-06-27 22:03 UTC, oSumAtrIX commented on android/settings.gradle
> +    id "com.android.application" version "8.2.0" apply false
```suggestion
    id "com.android.application" version "8.4.1" apply false
```

2024-06-27 22:03 UTC, oSumAtrIX commented on assets/i18n/strings.i18n.json
> +    "patchHistorySubtitle": "Last patched app",
"history" should be renamed to lastPatchedApp everywhere

2024-06-27 22:04 UTC, oSumAtrIX commented on assets/i18n/strings.i18n.json
> +    "removeAppDialogText": "Are you sure you want to delete this app?",
```suggestion
    "removeAppDialogText": "Are you sure you want to delete this backup?",
```

2024-06-27 22:04 UTC, oSumAtrIX commented on assets/i18n/strings.i18n.json
> +    "sizeLabel": "File size",
Seems to be unused

2024-06-28 16:43 UTC, BenjaminHalko commented
![Screenshot_20240628-094156_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/73490201/c8720d14-c0c7-4d67-ab4c-534ae17f8781)

2024-06-29 12:37 UTC, oSumAtrIX requested changes

2024-06-29 12:37 UTC, oSumAtrIX commented on assets/i18n/strings.i18n.json
> +    "noHistory": "No app found",
Should be called noSavedAppFound for example

2024-06-29 12:37 UTC, oSumAtrIX commented on lib/services/manager_api.dart
> +    // Removed saved app history if the file is not found.
```suggestion
    // Delete the saved app if the file is not found.
```

2024-06-29 12:37 UTC, oSumAtrIX commented on assets/i18n/strings.i18n.json
> +    "noHistory": "No app found",
```suggestion
    "noSavedAppFound": "No app found",
```

2024-06-29 12:37 UTC, oSumAtrIX commented on lib/ui/widgets/homeView/last_patched_app_card.dart
> +                  t.homeView.noHistory,
```suggestion
                  t.homeView.noSavedAppFound,
```

2024-06-29 12:37 UTC, oSumAtrIX approved these changes

2024-06-29 12:38 UTC, merged