feat: allow changing languages
ReVanced/revanced-manager pull request #1450
Opened 2023-10-30 16:37 UTC by Ushie

2023-10-31 05:48 UTC, validcube commented
This will result in conflict for all PR targeting dev.

I suggest that we merged all PR before merging this.

2023-10-31 11:05 UTC, validcube requested changes
Bleep

2023-10-31 11:05 UTC, validcube commented on assets/i18n/strings.i18n.json
> +    "suggested":"Suggested: ${version}",
Missing space

```suggestion
    "installed": "Installed: ${version}",
    "suggested": "Suggested: ${version}",
```

2023-10-31 11:05 UTC, validcube commented on assets/i18n/strings.i18n.json
> +        "defaultText": "defaultText",
defaultText... *is this intended?*

```suggestion
        "defaultText": "Default",
```

2023-10-31 11:05 UTC, validcube commented on pubspec.yaml
> +    sdk: flutter
Two spaces, not four. grrr

```suggestion
  sdk: flutter
```

2023-10-31 11:05 UTC, validcube commented on pubspec.yaml
>  dev_dependencies:
Missing `slang_build_runner` as dev dependency

https://pub.dev/packages/slang#getting-started

2023-10-31 11:13 UTC, validcube commented on pubspec.yaml
>  dev_dependencies:
Fixed: 11086213276917d9ccefc80259d444460f264485

2023-11-05 06:54 UTC, Aunali321 commented
![image](https://github.com/ReVanced/revanced-manager/assets/48486084/01c7706c-f9fc-4f4a-9d8c-7b6be71f532a)

2023-11-05 06:57 UTC, Aunali321 approved these changes
![image](https://github.com/ReVanced/revanced-manager/assets/48486084/0c648740-26b2-4250-b1f6-de91a2948878)

2023-11-05 07:03 UTC, validcube requested changes
Bloop: The documentation should be updated to mentions that translation must be generated using the command:

```bash
dart run slang
```

because we are not using [slang build runner](https://pub.dev/packages/slang_build_runner)

----------------------------------------------------------

👀 Checkout the full conversation discussed @ `Discord/ReVanced (Team chat; private)`
https://canary.discord.com/channels/952946952348270622/952987428786941952/1168894670579966012

2023-11-05 11:30 UTC, validcube approved these changes
🥞 Tested & Approved

2023-11-05 11:32 UTC, oSumAtrIX commented
Are the translation strings supposed to be included in this PR? They should be added separately by Crowdin

2023-11-05 11:39 UTC, validcube commented
> @oSumAtrIX Are the translation strings supposed to be included in this PR? They should be added separately by Crowdin

I'm sure that they aren't supposed to be included because it's out-of-scope, I decided to add translation to this PR because the repository don't have translation merged yet and I don't really know how would I (automatically) add translation to the repository.

On top of that, the translation file have to be renamed from *.json to strings_*.i18n.json (strings_ are optional).

2023-11-05 11:41 UTC, Ushie commented
That change can be done in Crowdin, once this PR is ready to merge

2023-11-05 11:43 UTC, validcube commented
> @Ushie That change can be done in Crowdin, once this PR is ready to merge

This PR is ready to be merge into `dev`.

> @validcube I don't really know how would I (automatically) add translation to the repository because the translation file have to be renamed from *.json to strings_*.i18n.json

On top of that, the translation need to be clean up due to missing translation in base language

2023-11-05 11:44 UTC, oSumAtrIX commented
Alright, in this case, you can remove the translations via a commit which will be squashed with the rest of the commits

2023-11-05 11:48 UTC, Ushie commented
- [ ] Please work on the translation popup, the lack of actions makes it look odd so you can add an "OK" button or such
- [ ] Is there any way to use friendly language names? e.g. English (US)

2023-11-05 20:58 UTC, oSumAtrIX commented
@Ushie Can you assign the person who you refer to?

2023-11-07 13:32 UTC, validcube commented
> Please work on the translation popup, the lack of actions makes it look odd so you can add an "OK" button or such
> Is there any way to use friendly language names? e.g. English (US)

🥞 All of these have been fixed in 3c18c4e.

2023-11-10 10:18 UTC, Aunali321 approved these changes
Nice work!, looks good to me

2023-11-10 12:59 UTC, validcube approved these changes
🥞 Approved :troll, self-approved

2023-11-10 12:59 UTC, validcube reviewed
The only thing that left is to resolve conflicts and rebase changes on of latest dev branch

2023-11-11 08:43 UTC, merged