fix: Incorrect duplicate filename handling when exporting files
ReVanced/revanced-manager pull request #1538
Opened 2023-11-30 10:47 UTC by dhruvanbhalara

- fix: https://github.com/ReVanced/revanced-manager/issues/1527

2023-11-30 15:00 UTC, oSumAtrIX requested changes

2023-11-30 15:02 UTC, dhruvanbhalara commented on pubspec.yaml
> +      ref: "fix/incorrect_file_name"
Sure, will update with particular reference commit.

2023-12-01 04:22 UTC, dhruvanbhalara commented
> Hey, this change didn't fix it for me
> ![image](https://github.com/ReVanced/revanced-manager/assets/79272171/ba0064ad-cb69-4eb4-8a6e-fefe737d1f5a)
> 

Can you please remove local cloned package once and try again?

2023-12-01 12:22 UTC, Ushie commented
Locally building the APK then testing worked as intended
![image](https://github.com/ReVanced/revanced-manager/assets/79272171/e084b529-12c2-4a64-b668-39923a88ac15)

I think this may be an issue with our PR build workflow in this case

2023-12-01 12:24 UTC, merged

2023-12-01 13:13 UTC, TheAabedKhan commented
Why are you guys doing all these??

This line fixes the issue.

<img width="625" alt="image" src="https://github.com/ReVanced/revanced-manager/assets/39409020/c86c5bad-118e-42fe-8461-1054b57ab3da">