feat: output suggested version into patch log
ReVanced/revanced-manager pull request #1557
Opened 2023-12-06 13:14 UTC by validcube

```
- Patch Info
App: com.google.android.apps.youtube.music v6.28.52 (Suggested: Any)
Patches version: v2.202.0
Patches added: Background play, Vanced MicroG support
```

Closes: #1552 #1550

2023-12-06 14:25 UTC, Ushie requested changes

2023-12-06 14:25 UTC, Ushie commented on lib/ui/views/installer/installer_viewmodel.dart
> +      'Root permissions: ${isRooted ? 'Yes' : 'No'}', //
```suggestion
      'Root permissions: ${isRooted ? 'Yes' : 'No'}',
```

2023-12-06 14:25 UTC, Ushie commented on lib/ui/views/installer/installer_viewmodel.dart
> +      'Options changed: ${_formatPatches(patchesChanged)}', //
```suggestion
      'Options changed: ${_formatPatches(patchesChanged)}',
```

2023-12-06 14:25 UTC, Ushie commented on lib/ui/views/installer/installer_viewmodel.dart
> +      'Integration source: ${_managerAPI.getIntegrationsRepo()}', //
```suggestion
      'Integration source: ${_managerAPI.getIntegrationsRepo()}',
```

2023-12-06 15:00 UTC, TheAabedKhan commented
How about separating the app info into its own section? For example, use `- App Info` and place the package name, installed version, and suggested version on a new line for each.

2023-12-06 15:01 UTC, Ushie commented
Compactness is good, it allows it to be posted in more places like Discord where there is limits on message sizes

2023-12-10 20:18 UTC, Ushie approved these changes

2023-12-10 20:19 UTC, Ushie commented
> > Compactness is good, it allows it to be posted in more places like Discord where there is limits on message sizes
> 
> A downside of compactness is that in the GitHub app, code blocks don't line-wrap so you need to side-scroll. Same issue with txt files in most file readers on mobile.

You have to deal with this issue nevertheless, given that the list of patches added/removed is horizontal as well

2023-12-11 04:26 UTC, merged