Changed featureNotAvailableText to new shortened and simplified text
ReVanced/revanced-manager pull request #1625
Opened 2024-01-08 07:38 UTC by otahir-21

"This application is a split APK and cannot be selected. Unfortunately, this feature is only available for rooted users at the moment. However, you can still install the application by selecting its APK files from your device's storage instead."

to:

"This application is a split APK and can only be patched with root permissions at the moment. Obtain a full APK and select it from storage or install it and select it regularly."

2024-01-09 19:22 UTC, oSumAtrIX commented on assets/i18n/en_US.json
> +<<<<<<< Updated upstream
Something went wrong here, please look into it.

2024-01-21 08:05 UTC, validcube requested changes

2024-01-21 08:05 UTC, validcube commented on assets/i18n/en_US.json
> +>>>>>>> Stashed changes
👋 It looks like there's an issue here!

```suggestion
        "featureNotAvailableText": "This application is a split APK and can only be patched with root permissions at the moment. Obtain a full APK and select it from storage or install it and select it regularly."
```

2024-01-22 10:02 UTC, validcube approved these changes

2024-01-22 10:03 UTC, merged

2024-01-22 10:06 UTC, oSumAtrIX commented on assets/i18n/en_US.json
> +        "featureNotAvailableText": "This application is a split APK and can only be patched with root permissions at the moment. Obtain a full APK and select it from storage or install it and select
Fixed correctness and shortened solution. Installing and patching would require uninstalling.
```suggestion
        "featureNotAvailableText": "This app is a split APK and can only be patched and installed reliably by mounting with root permissions. However,  you can patch and install a full APK by selecting it from storage."
```