feat: Add file and folder selection functionality
ReVanced/revanced-manager pull request #1941
Opened 2024-06-02 14:44 UTC by Francesco146

fixes #1703

2024-06-02 15:05 UTC, Francesco146 commented
ops, i opened the PR for the main branch, not sure what will happen if i change it to the dev branch

2024-06-02 15:41 UTC, Francesco146 commented on lib/ui/widgets/patchesSelectorView/patch_options_fields.dart
>  import 'package:flutter_file_dialog/flutter_file_dialog.dart';
waiting for the possible branch switch, this import is not needed anymore

2024-06-03 06:22 UTC, Francesco146 commented on lib/ui/widgets/patchesSelectorView/patch_options_fields.dart
> +                          await Permission.manageExternalStorage.request();
here maybe request the permission only if the platform is Android 11+

2024-06-04 21:03 UTC, Francesco146 commented
ready for review

2024-06-24 12:19 UTC, Francesco146 commented
update:

this PR has been merged in RVX Manager, many people have already tested it and it has no problems

2024-06-24 16:28 UTC, validcube requested changes
📝 Review: Analysis & Formating

(Note-to-self: Revisit this to test on physical devices when have time.)

2024-06-24 16:28 UTC, validcube commented on lib/ui/widgets/patchesSelectorView/patch_options_fields.dart
> +import '../../../services/manager_api.dart';
🔥 Avoid using relative import.

```suggestion
import 'package:revanced_manager/app/app.locator.dart';
import 'package:revanced_manager/services/manager_api.dart';
```

2024-06-24 16:28 UTC, validcube commented on lib/ui/widgets/patchesSelectorView/patch_options_fields.dart
> +import 'package:device_info_plus/device_info_plus.dart';
🤔 These appears to be unused.

```suggestion
```

2024-06-24 17:15 UTC, Francesco146 commented
> (Note-to-self: Revisit this to test on physical devices when have time.)

i tested the latest commit with an Android 14 virtual emulator, 10+ should be covered. consider testing on Android 9

2024-06-29 12:31 UTC, Francesco146 commented
tested on AVD Android 9. working as expected

2024-06-29 12:34 UTC, merged

2024-06-30 06:06 UTC, kitadai31 commented
I tried this but it's currently broken...
There are mistakes when resolved a conflict

5c68d51 added a [new import](https://github.com/ReVanced/revanced-manager/commit/5c68d513a38dcca1b884429c28f5bb32697bf37d#diff-6575bf694d851412b87d3899a829b95c173207ab57d4f9b239597795923f41fcR6), but it was deleted by this merge, so build fails.

Also, 5c68d51 changed a [value strings of PopupMenuItem](https://github.com/ReVanced/revanced-manager/commit/5c68d513a38dcca1b884429c28f5bb32697bf37d#diff-6575bf694d851412b87d3899a829b95c173207ab57d4f9b239597795923f41fcL505-L516), but this change was [lost](https://github.com/ReVanced/revanced-manager/pull/1941/files#diff-6575bf694d851412b87d3899a829b95c173207ab57d4f9b239597795923f41fcR535) while resolving conflict.
Therefore, when I press "Select file path" or "Select folder", nothing happens.

2024-06-30 07:12 UTC, Francesco146 commented
should I open another PR? conflict resolution was not included in the goal of this PR

2024-06-30 10:01 UTC, Ushie commented
Yes, open one please

2024-08-09 18:42 UTC, Francesco146 commented
@oSumAtrIX this was reverted in 1.21

2024-08-09 18:43 UTC, oSumAtrIX commented
Another commit supposedly fixed it according to @TheAabedKhan

2024-08-09 18:44 UTC, Francesco146 commented
doesn't seem like so on my part

2024-08-09 18:45 UTC, oSumAtrIX commented
Open a new issue

2024-08-09 18:51 UTC, Francesco146 commented
https://github.com/ReVanced/revanced-manager/issues/1703

there's already an issue open for this, basically this implementation gets a path as a content URI, that doesn't work with the patcher. the dependency that I added opens the system file/folder picker and returns the absolute path of what was selected. absolute paths works with the patcher and solves the missing permissions that A11+ requires

2024-08-09 18:53 UTC, oSumAtrIX commented
The PR was reverted because of it breaking entering null in patch options:

https://github.com/ReVanced/revanced-manager/pull/1941/files#diff-6575bf694d851412b87d3899a829b95c173207ab57d4f9b239597795923f41fcL545-L549

2024-08-09 18:54 UTC, Francesco146 commented
okay, I'll create another pr that handles that? or someone is already working on it?

2024-08-09 18:57 UTC, oSumAtrIX commented
The linked issue is not assigned to anyone yet, so sure.