feat: Improve unsupported patch warnings
ReVanced/revanced-manager pull request #2066
Opened 2024-07-17 22:57 UTC by Ushie

![image](https://github.com/user-attachments/assets/ddf720a1-64ee-4ee6-b1a2-bff67d2c02f7)

![image](https://github.com/user-attachments/assets/f856e991-18c1-4ff7-9b66-c5a71e7ce3cf)

2024-07-18 07:47 UTC, validcube commented
If supported version entries is more than 5, I'd suggest putting it incorporating progressive disclosure design.

2024-07-18 10:03 UTC, oSumAtrIX commented
What do you progressively dusclose here

2024-07-26 15:35 UTC, Axelen123 requested changes

2024-07-26 15:35 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +                            }
Use `else if` instead of nesting

2024-07-26 15:35 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +fun UnsupportedPatchesDialog(
Make the dialog functions `private`

2024-07-29 14:41 UTC, Axelen123 requested changes

2024-07-29 14:41 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> -    title = { Text(stringResource(R.string.unsupported_app)) },
Remove the old resource

2024-07-29 15:21 UTC, merged