feat: Add confirm dialogs when toggling dangerous settings
ReVanced/revanced-manager pull request #2072
Opened 2024-07-20 14:51 UTC by TheAabedKhan

Note: Strings need to be set

2024-07-20 15:08 UTC, Axelen123 requested changes

2024-07-20 15:08 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/settings/BooleanItem.kt
> +            }},
Add a newline here

2024-07-20 15:08 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/settings/BooleanItem.kt
> +    isSafeguard: Boolean = false,
This parameter can be removed if you rename the overload to `SafeguardBooleanItem` and copy the original function from the `compose-dev` branch

2024-07-20 15:08 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/settings/BooleanItem.kt
> +    suggestedValue: Boolean = false,
You can get this from the `preference` if you make `Preference.default` public

2024-07-20 15:08 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/SafeguardConfirmationDialog.kt
> +fun SafeguardConfirmationDialog(
Move this file to `ui/component/settings`

2024-07-20 15:55 UTC, Axelen123 requested changes

2024-07-20 15:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/settings/SafeguardBooleanItem.kt
> +    @StringRes confirmationText: Int = 0
```suggestion
    @StringRes confirmationText: Int
```

2024-07-20 15:58 UTC, Axelen123 approved these changes
The UI code looks good to me

2024-07-21 16:07 UTC, validcube requested changes
🔥 The dialog's title & description for safeguard must tell the user what the feature does and the consequences of enabling/disabling it.

* (consequences): https://m3.material.io/foundations/content-design/style-guide/ux-writing-best-practices#d7f04666-89f8-4795-a563-16d060b5ccf2
* (_not really important that much_, title): https://m3.material.io/components/dialogs/guidelines#0cff8b6b-d4f3-4442-8194-31212f5d1a12

![image](https://github.com/user-attachments/assets/dcb77fba-c0cb-4eeb-b098-21609252bd5a)

Additionally, this isn't very clear to the user, 

"Enforce selection of the suggested app version"
* Yes (Toggle the preference - which is on by default)
* No (Dismiss the dialog)

~~I assume you already knew that, so this is just a red flag check to tell maintainer to not accidentally merge.~~

2024-07-26 15:28 UTC, Axelen123 commented
Are there strings in flutter manager that could be used for this?

2024-07-26 16:33 UTC, TheAabedKhan commented
> Are there strings in flutter manager that could be used for this?

We have these two in flutter

```json
{
"enablePatchesSelectionWarningText": "Changing the selection of patches may cause unexpected issues.\n\nEnable anyways?",
"requireSuggestedAppVersionDialogText": "Selecting an app that is not the suggested version may cause unexpected issues.\n\nDo you want to proceed anyways?"
}
```

2024-07-29 09:47 UTC, Axelen123 commented
I guess those strings can be reused

2024-12-23 15:35 UTC, merged