fix: `ExtendedFloatingActionButton` not accessible by screen readers
ReVanced/revanced-manager pull request #2080
Opened 2024-07-24 08:30 UTC by TheAabedKhan

2024-07-24 12:09 UTC, Axelen123 requested changes
Each `ExtendedFloatingActionButton` already has text. Won't this result in duplicates when the buttons are expanded?

2024-07-24 12:09 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +                    setValue = { set(key, it) })
Add a newline

2024-07-24 14:09 UTC, optimatrix0 commented
Now the button is accessible, I really appreciate that.

2024-07-24 17:51 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +                    })
Expand it so it looks like this:
```kt
                OptionItem(
                    option = option as Option<Any>,
                    value = value,
                    setValue = {
                        set(key, it)
                    }
		)
```

2024-07-28 15:29 UTC, Axelen123 approved these changes

2024-08-06 00:46 UTC, merged