Fix: Resolve EACCESS error in special cases
ReVanced/revanced-manager pull request #2135
Opened 2024-08-11 17:39 UTC by BenCat07

Sometimes, when there is an attempt to patch an App, that APK is only marked as `r-x` and not `rwx`.  

This can cause the patch to fail, as it cannot read the file after copying it to `patcher/tmp-.../in.apk` 

This PR Fixes that issue (as far as i can tell; tested with brand new install of revanced manager, with and without patch. To Verify)

2024-08-11 17:46 UTC, oSumAtrIX requested changes
The changes in this PR should not be necessary and also doesn't explain why the issue only occurs sometimes.

2024-08-12 15:51 UTC, BenCat07 commented
Cause: Dart/Flutter had no built in permission management system, and the Copy operation of Dart copies the attributes of the original file, including read/write perms.

Why Missing write perms cause `File(path)` to fail, even when it could have been read-only, i do not know, and it would probably need to be checked in java/kotlin docs.

2024-08-12 15:52 UTC, BenCat07 commented
FileReader instead of File is probably a better idea.

2024-08-12 16:07 UTC, oSumAtrIX commented
Why is Manager copying the file and trying to write to it in the first place?

2024-08-12 16:09 UTC, BenCat07 commented
the "in.apk" is copied to "out.apk". No reading or writing in that case. Could replace the in.apk File with a FoleReader.

Would still need to fix the perms for "out.apk" after patching is complete though

2024-08-12 16:10 UTC, BenCat07 commented
> Why is Manager copying the file and trying to write to it in the first place?

So to answer this, it isn't writing to it at all. Hut java.io.File seems to be unable to open a file unless that file as a write flag set

2024-08-12 16:16 UTC, BenCat07 commented
Oh, actually, it seems the backtrace was not accurate due to release mode

```kt
patcherResult.applyTo(inFile)
```


This seems to be the culprit, it applies the patches to in.apk, then signs it and spits out out.apk

2024-09-19 22:59 UTC, oSumAtrIX commented on android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
> +        inFile.setWritable(true)
```suggestion
        // Necessary because the file is copied from a nonwriteable location.
        inFile.setWritable(true)
```

2024-09-19 22:59 UTC, oSumAtrIX approved these changes

2024-09-19 22:59 UTC, merged

2024-09-20 02:45 UTC, BenCat07 commented
pog