update rules of analysis_options.yaml. and solved all problems
revanced/revanced-manager pull request #665
Opened 2023-01-27 18:07 UTC by j-j-gajjar

2023-01-27 18:32 UTC, j-j-gajjar commented
Hello @Ushie,
Because of the changes that I have made in the analysis file, this problem is being generated in the project, so I have tried to fix it.
<img width="1251" alt="Screenshot 2023-01-27 at 11 59 44 PM" src="https://user-images.githubusercontent.com/57590688/215166183-8783de50-c5ba-4927-9319-fa4f9e3660b0.png">

2023-01-29 22:20 UTC, Ushie requested changes

2023-01-30 07:20 UTC, j-j-gajjar commented on lib/ui/views/app_selector/app_selector_view.dart
> +      onViewModelReady: (model) => model.initialize(),
onModelReady' is deprecated and shouldn't be used. Prefer to use onViewModelReady instead.
Try replacing the use of the deprecated member with the replacement.

![image](https://user-images.githubusercontent.com/57590688/215412019-b63a605b-632e-4273-a58f-676b5d99bc07.png)

2023-01-30 12:35 UTC, merged

2023-01-30 15:51 UTC, j-j-gajjar commented
@Ushie 
Please try to verify the Dart analyzer whenever a reviewer merge a PR.

<img width="967" alt="Screenshot 2023-01-30 at 9 20 49 PM" src="https://user-images.githubusercontent.com/57590688/215525605-92f4935d-0dcf-44c8-81ff-f2b72f086e0f.png">

2023-01-30 15:55 UTC, Ushie commented
> @Ushie Please try to verify the Dart analyzer whenever a reviewer merge a PR.
> 
> <img alt="Screenshot 2023-01-30 at 9 20 49 PM" width="967" src="https://user-images.githubusercontent.com/57590688/215525605-92f4935d-0dcf-44c8-81ff-f2b72f086e0f.png">

Sorry about that! seems like I missed that one, I'll pay more attention next time