feat: confirmation dialog for deleting keystore
revanced/revanced-manager pull request #764
Opened 2023-03-29 07:21 UTC by EvadeMaster

## ✨ - Confirmation dialog for deleting keystore

What a coincidence, this PR have almost the exact same wording as the issue that I was resolving.

Resolve: #566

2023-03-29 07:49 UTC, Ushie requested changes

2023-03-29 07:49 UTC, Ushie commented on assets/i18n/en_US.json
> +        "deleteKeystoneDialogText": "Are you sure you want to delete the keystore used to sign the app?",
```diff
- "deleteKeystoneDialogText": "Are you sure you want to delete the keystore used to sign the app?",
+ "deleteKeystoneDialogText": "Are you sure you want to delete the keystore used to sign patched applications?",

2023-03-31 02:56 UTC, Mipirakas commented on assets/i18n/en_US.json
> +        "deleteKeystoneDialogText": "Are you sure you want to delete the keystore used to sign patched applications?",
Typo, you wrote keystoNe. In the 
_showDeleteKeystoneDialog function name as well.

2023-04-01 09:27 UTC, Aunali321 approved these changes

2023-04-01 09:33 UTC, Ushie approved these changes

2023-04-01 14:02 UTC, merged