feat: show warning dialog for unsupported versions
ReVanced/revanced-manager pull request #869
Opened 2023-05-13 12:47 UTC by andrisas

closes #866

2023-05-13 12:55 UTC, Ushie commented
If I'm an armv7 user, this dialog will never be shown to me

2023-05-13 12:56 UTC, Ushie requested changes
If I'm an armv7 user, this dialog will never be shown to me

2023-05-13 12:56 UTC, Ushie commented on assets/i18n/en_US.json
> +        "versionWarningDialogText": "Patching this version is not recomended and might fail. Proceed anyways?"
```diff
- recomended
+ recommended
```

2023-05-17 07:39 UTC, Ushie requested changes
Universal and experimental patches shouldn't work as a bypass to this dialog

2023-05-17 15:00 UTC, Ushie requested changes
Can you do a few things?

- [ ] show this when selecting the application, instead of starting patching
- [ ] include the supported version in the dialog somewhere
- [ ] maybe show select from storage instead of continue anyways? I'm not sure about that so let's wait for @Aunali321 on that

don't revert your changes refactoring the armv7 dialog to showWarningDialogs, its likely to be of use in the future

2023-05-17 18:33 UTC, Aunali321 commented
If you go with restricting, you should account for the entire compatibility list, as the latest suggested version isnt the only supported one

2023-05-19 18:31 UTC, Ushie requested changes
Over the course of this commit, "recommended" is mistyped as "recomended"

2023-05-19 18:32 UTC, Ushie requested changes

2023-05-19 18:32 UTC, Ushie commented on assets/i18n/en_US.json
> +        "versionWarningDialogText": "Patching this version is not recommended and might fail. The recomended version is {recomendedVer}. Proceed anyways?"
Over the course of this commit, "recommended" is miswrote as "recomended"

2023-06-07 16:54 UTC, Ushie commented on lib/ui/views/app_selector/app_selector_viewmodel.dart
> +        locator<PatcherViewModel>().selectedApp!.packageName);
Could you check whether the installed version matches any of the versions in the compatibility list?

2023-08-28 00:32 UTC, closed without merging