fix: typo version
revanced/revanced-manager pull request #895
Opened 2023-05-24 20:44 UTC by MrAngelos6

Fix: #894
There is already a "v" before the version number thanks to the workflow. So now it's useless to write it in the string.

2023-05-24 20:54 UTC, HokoraYinphineMPP commented
Pushing into main?

2023-05-26 10:11 UTC, Ushie requested changes
Does latestManagerVersion always include `v` in the string?

2023-05-26 10:50 UTC, EvadeMaster commented
> Does latestManagerVersion always include `v` in the string?

Yes indeed, ReVanced Manager get `latestManagerVersion` from [ReVanced API Tools](https://releases.revanced.app/tools), the response data from ReVanced API already included "v", so there's no reason to include it.

https://github.com/revanced/revanced-manager/blob/8af62b917ce284b907da048b30f28bd94087f370/lib/services/revanced_api.dart#L100-L119

2023-05-26 10:54 UTC, Ushie approved these changes

2023-05-26 10:54 UTC, merged