chore: merge `dev` branch to `main` branch
revanced/revanced-manager pull request #996
Opened 2023-07-05 13:02 UTC by EvadeMaster

## Merge `dev` branch to `main` branch

2 Commits 1+1)

* 🐛 1 Bug Fix
* 🧹 1 Build Change

--------------------

ReVanced Manager v1.3.8

2023-07-08 14:44 UTC, TheAabedKhan requested changes
No semicolon on 119 and 120??

2023-07-09 23:34 UTC, EvadeMaster commented on lib/ui/widgets/settingsView/settings_export_section.dart
> +              _settingsViewModel.resetSelectedPatches()
Hmm? What about it, the code seems to work fine as intended.

2023-07-10 06:26 UTC, TheAabedKhan commented on lib/ui/widgets/settingsView/settings_export_section.dart
> +              _settingsViewModel.resetSelectedPatches()
Oh, I missed the `=>`

2023-07-10 13:04 UTC, TheAabedKhan approved these changes
This looks great ✨

2023-07-10 13:56 UTC, merged